# Generated by Django 3.2.3 on 2023-02-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20230202_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_generalmanager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_storemanager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
    ]
