# Generated by Django 3.2.3 on 2023-02-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20230202_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_generalmanager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_storemanager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(default=True),
        ),
    ]
