# Generated by Django 3.2.3 on 2023-02-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20230203_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_generalmanager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_storemanager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('General_manager', 'General_manager'), ('Store_manager', 'Store_manager'), ('Worker', 'Worker')], default='Worker', max_length=100),
        ),
    ]
