# Generated by Django 3.2.3 on 2023-02-10 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_auto_20230203_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField()),
                ('worker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('asset_cls', models.CharField(max_length=200)),
                ('periodcat', models.CharField(max_length=200)),
                ('Useful_life', models.CharField(max_length=200)),
                ('Remain_life', models.CharField(max_length=200)),
                ('Warehouse_location', models.CharField(max_length=200)),
                ('Qr_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.qr')),
                ('verification_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.verification')),
            ],
        ),
    ]
