# Generated by Django 3.2.3 on 2023-02-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_assets_qr_verification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assets',
            new_name='item',
        ),
    ]
