# Generated by Django 3.2.3 on 2023-02-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_rename_assets_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
