# Generated by Django 3.2.3 on 2023-02-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_alter_verification_worker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='verification_id',
        ),
        migrations.AddField(
            model_name='verification',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.asset'),
        ),
    ]
