# Generated by Django 3.2.3 on 2023-04-02 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_auto_20230213_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=200)),
                ('sessionStartDate', models.DateField()),
                ('sessionEndDate', models.DateField(null=True)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='verification',
            name='date_time',
        ),
        migrations.AddField(
            model_name='asset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 19, 9, 46, 864839, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verification',
            name='sessionId',
            field=models.CharField(default=datetime.datetime(2023, 4, 2, 19, 9, 54, 475148, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('General_manager', 'General_manager'), ('Super_admin', 'Super_admin'), ('Worker', 'Worker')], default='Worker', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='geo_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='verification',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('flag', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Warehouse_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.location'),
        ),
    ]
